name: Build NIF Preview Plugin

on:
  push:
    branches: main
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Build NIF Preview Plugin
        uses: ModOrganizer2/build-with-mob-action@master
        with:
          mo2-third-parties: libbsarch
          mo2-dependencies: DirectXTex cmake_common uibase
      - name: Set version env
        run: |
          sed -n 's/.*return[[:space:]]*{\([0-9]\+\),[[:space:]]*\([0-9]\+\),[[:space:]]*\([0-9]\+\),[[:space:]]*[0-9]\+,.*/version=\1.\2.\3/p' ./build/modorganizer_super/${{ github.event.repository.name }}/src/PreviewNif.cpp >> $GITHUB_ENV
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: preview_nif_${{ env.name }}
          path: |
            ./build/modorganizer_super/${{ github.event.repository.name }}/vsbuild/src/RelWithDebInfo/preview_nif.dll
            ./build/modorganizer_super/${{ github.event.repository.name }}/**/data/shaders/*
